seed: 42
debugging: false
scaler: min_max
sin_pos_enc: false
sin_pos_const: false
encoding_dropout: 0.1
handle_constants_model: true
num_assets: 8
sub_day: false
ssm_config:
  bidirectional: false
  enc_conv: true
  init_dil_conv: true
  enc_conv_kernel: 5
  init_conv_kernel: 5
  init_conv_max_dilation: 3
  global_residual: false
  in_proj_norm: false
  initial_gelu_flag: true
  linear_seq: 15
  mamba2: true
  norm: true
  norm_type: layernorm
  num_encoder_layers: 2
  d_state: 128
  residual: false
  token_embed_len: 1024
  block_expansion: 2
  chunk_size: 256
  headdim: 128
num_epochs: 100
training_rounds: 200
validation_rounds: 50
real_test_interval: 5
lr_scheduler: cosine
initial_lr: 5.0e-05
learning_rate: 1.0e-07
t_max: -1
context_len: 256
min_seq_len: 30
max_seq_len: 256
pred_len: 60
pred_len_min: 10
pred_len_sample: true
batch_size: 64
no_pos_enc: false
loss: nll
beta_kl: 0.1
multipoint: true
sample_multi_pred: 0.5
diag_prints: true
nll_detach: true
wandb: false
continue_training: false
version: v2_multi8_exchange
real_train_datasets:
- exchange_rate
real_test_datasets:
- exchange_rate
